name: Build
on: [release]
jobs:
  Build:
    
    strategy:
      matrix:
        os: [ ubuntu-18.10 ] # macos-latest, windows-latest
        go: [ 1.13 ] # 1.12, 1.11

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Build
      run: |
        go build -o ./gong

    - name: Test artefact
      run: |
        mkdir e2e_test
        mv ./gong e2e_test/gong && cd e2e_test
        ./gong 

    - name: Upload artefact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./gong
